### ISSUE TITLE
Custom headers are not resizable.

### ISSUE THREAD

**Issue by VigneshSubramaniam** [Autodesk/react-base-table#127]
Hi @nihgwu, When we provide a custom headerRenderer, the columns are not resizable. Is there a way we could enable that?

**Comment by nihgwu** [comment]
`headerRenderer` will make the table to use your implementation of header instead of the builtin one, so you have to implement on your side, but I'd say `headerRenderer` is not for this kind of case, it's for the case you want to display something different from cells, like a title or summary. I think `column.headerRenderer` should be enough for most cases

**Comment by vignesh-subramaniam** [comment]
Oops. Didn't notice that. Thanks man. Awesome!!

**Comment by VigneshSubramaniam** [comment]
Oops. Didn't notice that. Thanks man. Awesome!!
