### ISSUE TITLE
Tooltip unexpected behavior

### ISSUE THREAD

**Issue by philxavier** [Autodesk/react-base-table#150]
Hello folks! 

I'm running into this issue and wondering if someone might have found this problem (and a solution) before. 

Table at regular screen display = tooltip not working event though text is truncated =(
![table1](https://user-images.githubusercontent.com/7192635/81362678-67995500-90af-11ea-92e6-c046a9e20868.jpg)

Table with browser reduced a little in size = tooltip working just fine =)
![table2](https://user-images.githubusercontent.com/7192635/81362746-8f88b880-90af-11ea-8b5b-7c0adacde46c.jpg)

Anyone has any idea?
Thanks a lot!

**Comment by nihgwu** [comment]
Hey @philxavier , I think that's a IE/Edge only issue, we have the problem too in internal usage, the root cause is that we are using `scrollWidth` and `offsetWidth` to decide whether to show the tooltip, but one of the value is float and other is int, and the the float value would be floored, then there would be a mismatch, so there won't be easy solution, what I can think about is using the canvas to measure the `offsetWidth`. BTW we are going to drop the support for IE and old Edge in our products

**Comment by philxavier** [comment]
Hey @nihgwu , thanks so much for the prompt response! I’m just a little confused.. are you saying that this should only happen with IE/edge ? In my case, I was using Chrome... 😮

**Comment by nihgwu** [comment]
what's the tooltip component you are using?

**Comment by philxavier** [comment]
React-texty. Should it work with different one?

**Comment by nihgwu** [comment]
@philxavier you can use any tooltip component which meets your needs, but I think we are not talking about the same issue, for mine the tooltip would show up even it's not truncated on IE/Edge, but for yours, the tooltip doesn't show even it's truncated, I think the reason is that the `scrollWidth` and `offsetWidth` is the same as the available space for the element, I'd say that's really a very edge case

**Comment by philxavier** [comment]
Got it! Thanks so much for your feedback !
