### ISSUE TITLE
How to make cell highly adaptive and change cell style

### ISSUE THREAD

**Issue by condorheroblog** [Autodesk/react-base-table#154]
I found a way to customize cells through the example of extra props on the official website. Apart from the example properties you demonstrated, I tried to add styles and class names. It's useless. Can you tell me how to implement them. I just want to add a border right to the cell to make the table look more like excel.

The second problem is that if there are too many cell contents, ellipsis will appear. Can react-base -table not set the overflow ellipsis attribute like antd's table, and display the cell contents too wide and automatically wrap instead of omitting。

不过，你这个无限滚动做的真好，牛👍

**Comment by nihgwu** [comment]
You can't set `style` via extra props, the reason is that the style is an object which is easy to break the inner optimization(pure component) which has inner style already for virtualization, you can't set `className` via extra props either, instead you should use `Column.className` for cells and `Column.headerClassName` for header cells, those two props both support to receive a function

for the second question, right now `BaseTable` only support fixed row height, so auto wrap the text is not supported which requires dynamic row height, this feature would be implemented in the next major version, but internally we only use table with fixed row height actually

**Comment by nihgwu** [comment]
BTW for cell styling, you can simply select the cells via `.BaseTable__header-cell, .BaseTable__row-cell`

**Comment by danielrey28** [comment]
@nihgwu I'm having a similar issue where I'm trying to override the style that gets added to the cell. I'm trying to do it via the .BaseTable__row-cell class but it seems that whatever I set there gets overridden by the overflow:hidden style. Any suggestions would be greatly appreciated!

**Comment by danielrey28** [comment]
@nihgwu NVM. I was able to resolve the css issue. Thanks!

**Comment by nihgwu** [comment]
hey, @danielrey28 it's recommended not overriding the `overflow: hidden` style, instead you should use a `Portal` to render the overflow element outside of the cell

**Comment by danielrey28** [comment]
@nihgwu Thanks for the portal recommendation. I'll take a look. Why is overriding the overflow style not recommended? What are the side effects?

**Comment by nihgwu** [comment]
what if the overflowed content is in the last row, and the table's bottom is near the viewport's bottom line, then you won't see the overflowed content, with `Portal` like `react-popper`(we use it internally) could place the content according to the available space automatically

**Comment by danielrey28** [comment]
Gotcha. I'll try using the portal instead. Thanks again!
