### ISSUE TITLE
Re-rendering a component with estimatedRowHeight is causing unwanted recalculation of height 

### ISSUE THREAD

**Issue by ajbee07** [Autodesk/react-base-table#226]
For example in my initial load I declare a baseTable with estimatedRowHeight property, then it will render with no problem.

Then I unmount it(Change Tab or Page) and I return to the page with the the baseTable with estimatedRowHeight, it will render from minimum height to the correct height causing unwanted animation or flicker in a sense that it's like moving from height 30 to let's say the row is height 100.

Is there a way to make the animation(changing of height) not visible in rendering or any way to hide it during the re-render? 

Thank you in advance.

**Comment by nihgwu** [comment]
I think the flicker only noticeable in dev mode, you can try on production mode, here is a [demo](https://autodesk.github.io/react-base-table/playground#MYewdgzgLgBAJgQygg4gUzGgTkkWYC8MAFAJSEB8JA3gFAwwCWcAXDAGYIDW2AdDmDggAtrwCuY5mQA09GGATC0bTjyy8FS3u0aCAcorQy5AcwxxsK7nwFDRAIxAgANmgRgyMAPwwA5MIRXXxg2X3Y0AKDZBghQLGUYOgYGAKgACys1fnc7DTFhe2xiAHYABnIAahgAZlLomABfevtGLHTEAE9MvkQoNF5CqAB3NAxiAEYATkmAVmkYACZS0pnSeqRkYDSlMCgIbvVbETyCotX6i1isRgAHKEZwA95nPAjeCAw+sGAjNbkIhCMZxPXR9LCYKC8AFA4wMUBiXZYLocazqBBwODxCAQXjwxEdWEwdGYtDYthJZLQeJoKBPYlYnFU0ZQACCGIZhLhjCgyNUfHppJxwG5BL+yRgAC9bgBhEAWOnswW8KU3WUWQlNWgNUi0WigSCwdCCbCy3aAzD4IjQDquOC8OCMABuAAM5PYEMAuCYsCAEXAALSgF5YNgAEmoNx9NwglDkDEjIGjvDMxstBCI-kCaGCPl8zkYJjSUHszjE2ZCfhuui4vgaAG45EG8GwhmluWgGwxHFgLFh-TgHWJ9jUbgAPTswIbMdJsJZjidpNAFouz0rzuTscBQf0QRgShLjABs64Ym92-pGy9pMEczjgE-zmH9i6vq5PMD6o+3gQLYDYP12bAG1dPVwGgGAjV7QgaBgFMoO1SgSDkAAeSCTS3c1sFg8xsAIag4OwBoKDjRICLTDNInLXNACEyYJQkAATJaxQgB6NCsFNZBdGwYidVAg0YAAZTiNBoOtW13hudxXThFxmxgcME2jRDiEUxlhJgCgiEPUpvD8b1RjAOi-HiOBfFIetaBA-VwJZKBNm2T5RJ5cSHRdN0PS9H0-UDWSQxgfNCygb0EA6CcpzgGdFjXcc5BfQK3xihhHzQZ8l3iqL30-b8Ar-GAALBCdu17ft0UYIc2AAFnfJs-OC0LLN1azYAsTgxGcKAABEkAQaDMCGGAWSwHACRmZZyjkbQgWcYhxoYXgAhuYhelQDBsFwLAdTmiA8CgYhiAQeZ7HIAgqH2jRDA0m9zqUXTxgrf1xlIXimvgNBWvagSdug6gYB4ZFfE0bN5jwXs2E+toAHkez4FkBOlRpdTQUcbi+lqEDa2BgGcBBsQGm4bhgJGvjgGMACU3GASFZWEFHMF2RI5GgJARKICkGGWtg0YxrrkHqGIdoAIWRLmPp2vmYAgNIQCGNgoCwMt6gaXUZNLYRIGggBtEi2eSP7QkB3xxYYe4oFcUIDCUQ2SPZ7qAGk0H+g2jcnacMhgcZRudrE9wQEsEjlhXrYlnbfbNj95bQZ32B9fdctlVWwF4AAxGOMA61o0Eph5E4AGQAUSTgAVcXNXFHWGD1vxYleK3xWN7kw98ISa+d5b7f+6v4nmpA0lruvwsi7TnZ-Ew45cfJE5ZHKdipvO9ELvPSed7a2lDhJOGcD4S-F8vfod0IyL78UTcb6jGNbu3970nCsCP5IfmcZxydTSwYIf5weYQNgyMaY6qFQm+2FUx4TIg0GAzEKDOwHm7IeQcR5jwTrwKev4Z68GlHPBeS8g4r2QH7WWEdt7ayDpXXwLQ2hpE6HfeupsEi+AFq0doIUqHwEvv9MhjCOjMOWugOyr9iA-SDBPeYPohif1-rGOuyQRGfw1oItW9pWEAF1eBQBADnEAwAsw8zQAJOWugTCcmSNAtg4xljDxymweOE8kHT0+LwUmABJFAAAJYu2CQ54PDoHcUpdki7xIRsD0DldgQGYSfWhtl7Iz1CRfZA7dQiBK2NE5hxiYCwMkfAyx495HINHqg9B89F7O0XOibAz9ex8L-jAZCkSgkzwoF4ZCzFalJM+JAoO79ynYD4QItAj8xEIROtUlpwSoAUGoO-T+DQmkjPqYQsuxCr6+EuMAa4dxs5hIbrQjqpJVm3HuOALhrDQgrLWQcwyUDXarjqEHb2Eo174O8XXHBDyvGRxIr4hg-ilnQmcJsmhoQ84BCBEcuJPzgV-MuRFN2SwbmSLua8gO7zJEvM8Ui+ZfjFn-TxHLThztwmhFlAiXFoKEDxL8DipEKSrnuzMbc0kPs0UEPcavJlTyGCfIZpIgJipsT-MbmyEkfLYlkqWQKbE7w5bMmpdC65XsGX3LZci5InLvn-Q9OcmVkVTFwrrpkmAVicm2N2GgjBRSg7RxALHLJiCU5WrThnLO4B7FONcc7TpN8ekwGkd1cRQziBBwYMhewYg7LgEDckcA0p8yejwp4IZu9JHpEYIyGkujmb8IjZIjmH42yMmQH0BRyBJrtSKKORCo5eDMBgAAQnTN66Wn8q1wDFJIuu2os2NCVm2jSnbybCBAI6NAEamkhrDWAYikjW0cvqIo5WMAo3ZLAODWAVpBYdEQjrF6IMsJrraELXgO7yKCR2lDXsSC4a3XuuMEiL1lqa14I+5N+bmZFoQHO8Uy13g7T2gdG8VT9oaxwQev6ijLr2CA+u3goHdJHvukep6JFn3vDTQWowu9gMdBFSXTaCM5DxFTJ4LdYFYA-WWvMTDFGpb9TAUQZDTM+gkXiFAMQ4IkKSOQpOttwbQ2qLAJ2qNMauBxqqYmuu9HUMZrEyi6jbAa2S2ls7SRHae0cu7W2rjPbC4gBMCYVwI7mJjr45puuPHx0CbANGxgsbqDxqoNJ5IEmoDpr6Jm1T4mdN6YSDW+jaGVGedcEp9tuGe0NHU5IkzkjtO6dcHlJdEADNGfAJF5IZm+MWaszZuzXL3O5pTSh5zaG3O5ZtsgNgGtuGrRwKorAMgYCPrfYooLPiQttrCxGlL4pBVMD6MID8IB+s3ES7x5L1AFP9QAGQTZgCOwua9O06FHGgOAna5GQDwp2hgNafN5sla+1RMWRI+GQ2txkMajB1BgBVcgstdunc7eFttpJ7ipGW6TaWzi0pFjwhVUoj3s3dTwstf7zz114UwyD8Ui6E4rrwsh6HE8V2Q-ARQEHTSTO4aVkrIAA)

From your description, seems it's not a re-render but re-mount, so all the cached row heights will be discarded and re-measure again, that's why the row height changes

**Comment by ajbee07** [comment]
you're right it's re-mount. Is there any function or indicator that I can use while the re-measure is happening? because I'm using the estimatedRowHeight extensively and the height change(re-measure) is very visible even in my production application.

**Comment by nihgwu** [comment]
Sorry I'm afraid there is no such api to know whether it's measuring or measured, but a workable solution is debounced `onRowsRendered`

**Comment by ajbee07** [comment]
Can you give an example on how to implement debounced onRowsRendered? thanks

**Comment by nihgwu** [comment]
as `onRowsRendered` will be called before and after the measurement, so I think a proper debounce like 20ms would make sure it's only called after measurement

here is an [example](https://autodesk.github.io/react-base-table/playground#MYewdgzgLgBAJgQygg4gUzGgTkkWYC8MAFAJSEB8JA3gFAwwCWcAXDAGYIDW2AdDmDggAtrwCuY5mQA09GGATC0bTjyy8FS3u0aCAcorQy5AcwxxsK7nwFDRAIxAgANmgRgyMAPwwA5MIRXXxg2X3Y0AKDZBghQLGUYOgYGAKgACys1fnc7DTFhe2xiAHYABnIAahgAZlLomABfevtGLHTEAE9MvkQoNF5CqAB3NAxiAEYATkmAVmkYACZS0pnSeqRkYDSlMCgIbvVbETyCotX6i1isRgAHKEZwA95nPAjeCAw+sGAjNbkIhCMZxPXR9LCYKC8AFA4wMUBiXZYLocazqBBwODxCAQXjwxEdWEwdGYtDYthJZLQeJoKBPYlYnFU0ZQACCGIZhLhjCgyNUfHppJxwG5BL+yRgAC9bgBhEAWOnswW8KU3WUWQlNWgNUi0WigSCwCyOBE-QgkdhgebCCBm8qURJyVywe5KEBiKAASTgAG45PEoGJwRwTfdwMReBGEFgTBByBS4a4owAVRiu93EF1oN2euCkX3izPZr1mj5QFNpqDETwEKgW3gIG43ZwE9KMCDzKMxtYwa15uQNX0D3X66AwdCCbCy3aAzD4IjQDquOC8OCMABuAAM5PYEMAuCYsG7BABaUAvLBsAAk1Buh5uNprcgYt5A994Zgnc4IRH8gTQwR8XxnEYEw0igexnDEf8Qj8G5dC4XwhzhFw8DYIY0m5NB8xgRwsAsLBjxwVcxH2GobgAD2woZmHSNglgo7C0jQECwLo0oGLkdhwCgY8IEYCUEnGAA2DiGC43ZjxGFjaRwlwfUdXQ0GPJjpLY0SYD6cieMCECwDYH5dmwX0tz1cBR3HfCzWIagYA-SztXtYg5AAHgsyduJnbBbPMbACGoOzsAaCgn0SAKvx-SJoMAwAhMmCUJAAEyRCXIAejcrAp2QRSsGCnVTINGAAGU4jQEseSXd4bncLdkPPK8bzvB8qGIF831iV4YAoIghNKbw-APUYwDivx4jgXxSCHEyR1gFkoE2bZPlKxc0GXVdN23Xd90PBE4FPFCLxgYDQKgA8EA6KiaIyRZ2MouQVKOtSboYYDMGU5j7qu9TNO0w69JgAywWw3D8MI9FGBItgABZ1LPVDbJwM7aEmszDTQTgxGcKAABEkAQM1MCGGAWSweHiBmZZyjkbQgWcYgKYYXgAhuYhelQDBsFwLAdXpiA8ErYgEHmexyBrEgEA0QwOpw8WlF68YYOPcZSFyqb4FRhB0agArebNGyeGRXxNH-eY8HwtgtbaAB5PC+BZArpUaXU0HIm5tYsNGMb+5wEGxQnGxgJ2vjgG0ACU3GASFZWEF3MF2B0YmQPodZClm2Dd9WMex5B6hiXmACFkTTjXzagbOYAgNIQCGNgoCwKD6gaXUavySAzQAbRC+Nkj10JDd8UuGHuKBXFCAwlD7kKGBZgBpNB9d7-uYGouBaJgcYyYXrF+IQCCEhruuJ7L3nt+HjTa7QBf2EPATftlSDhDAXgADEr4wTHWjQcOHgfgAZABRR+kyl01OKTuDBu5+DavEce4oB7chPr4IqrxoEwOnrPUIkD+ipDSMg8US8V7dQXjpEwN8XDN14CyH6OwI6-z0EmX+wcF48zaMfBInBnAfCAaXUBMBwG+DCjg5Ig94HRUSgvVB+t+ELx+M4ZwodPyWBoH9NAMjM4IDYGFRowsqCuR8vgMKfkwoNBgMlCgC88GXQIQfIhJC74PwobpKhvBpQ0LoQwg+TDkA72rmfThHcD68JaG0NInQBGwKHgkXwudWjtFOqE+AOMZ760CTEjocSWboFmgo6yf1SH33mIeIYqjNGUAPgwApqjW5njIeIgAurwKAIBv4gGAH+TOaACo110CYTkyRzFsHGMsQhP02C3zIfY4hjjg4ehQAACUAe4o+XjT773FMA5I3DeEbF3PNXYEA4lCIiTNOaVC9liISWgvwWytgnLiX0mAliYFEmGTAUZ99yGUM+E4lx9CF5MXRNgOR+EslaJgM5I52yqEUC8M5ZK4LrmfFMQfaRsjdFZJssiopDkRZgtmhChF1AMU4waDCuFOyoCItWVw-xFzfCXGANcO4X99lwIiZjUk9LbihkGmc5AiTQh0oZVy25F02J1APpvCULDvErJgR4qVyzz4hTWQwDZNLoTOGZeE0Iv8AhAjSec-W6rhXL0uksMVjyJXyr3oqx5cqlnWt8SA6l+s8Q11SQvA5oRZQIjdfq3lNLXVImNSvAZ5qYGWvtT4hZzDI0yoYMquOMDNmKmxJq+BbISSpp5QgPllyU2MhrsyYNprBnitJFvWNNrkgJtVfrXcQqzEitXqWx51iRm5LsR83YXzaE-IPpfEA19222Kfi-MAb94if3ALwKZsz5mPORYC7AaKYDlJxsUkWTlHkMGcvYd0DSwClOSOAaUwE9x+WrFQbhjzWyMhpB0pARhr3bpThpDCBbH0rhxlTDGRRyL2nIrwZgMAACE35V2V1UUB3MC9HnaiPfGhu26OoIZgKHYQIA1xoCPTCvds1wDBUeWKat9QamNxgCejtxcSx5w6PaTuKsTZeXnLR3gTHwqFV5lbfC5C7ay3luMEKKsWZtwjPU997wE79BZmR8ULN3i8yrALHCIL+atw8fnXgesamS3sOp1j2nersfluxpWIVb3vHvVJ6y0aoD52zUArmDsGByHAMHSuEAl0jTNEaI8PwlPRljPRoTZkXD9BeN03wbmPNeeWn3IkgWnNNCurlMpujPAMeRokeJWdD5tHs2XCuBMjFEAs9AR9IV-SBjACQA+zlCPbt3fu8AqGT1nq4BekFz6CwSdLA+voNnkO2qK2wED5dK6wZgfBobjQkPboa8hpMIATAmFcDh5KeGD0LZgU1-Dh6ZttcYOe6gl7E0zbK1Zx9g2ZuCOW6thIIGytSfqXd1wk3VlOeQw0ObjztuPKWyt1wOTbEQHW5tgjOHwf7aG4d47p3uuCN65dgbCO5M4zYK3dJbMcANKwDIGAYmZPverZ97d32j1-ZgRmpgfRhAaRAPTm4YPmtgAoNQcbBMABknOYA4aTCw1DOhyLLVQ1U++EA-KoYYCBx7vXnsNMByVHwFmxeQHeGeowdQYAQ3INXCTqvQczZ+9u0kLpH1wHc0MGZb0wJ+QhqUY3jyWZ+RZo72VtG-IaY6G78UlHbHFz8hZv3zdi4++PWAS3nnUVwEDxJ6LQwo-yLgGHkxbuYXbaS1qWgQA) you can change the debounce timeout to see the different
