### ISSUE TITLE
Visible row height changes when using dynamic heights

### ISSUE THREAD

**Issue by hirviid** [Autodesk/react-base-table#227]
We have a collapsible grid with 2 different heights. But because react-base-table either uses the same height for all rows, or recalculates the heights dynamically, we have this "jumping" effect when opening a parent item:

![802ee5884f10c2d8efca618f44b606af (1)](https://user-images.githubusercontent.com/6641475/91872329-0ad23380-ec78-11ea-811a-ec292644f264.gif)

In react-window, the rowHeight prop can be a function. I think something similar in react-base-table might solve that strange effect because we know all the heights up front. We don't really need dynamic heights, just variable heights. 

Is there a way we can prevent this "jumping" effect?

Thanks!

**Comment by nihgwu** [comment]
similar to #226, but you raised a good question, actually we are using `estimatedRowHeight` to implement the dynamic table instead of variable table which means all the heights are unknown at first, but I understand the assumption, what you need here is a variable table but it's not supported right now
