### ISSUE TITLE
How to keep position of the scrollbar when load more data

### ISSUE THREAD

**Issue by dohoangtung** [Autodesk/react-base-table#255]
Hi,

In the example "Infinitive Loading" (https://autodesk.github.io/react-base-table/examples/infinite-loading) I've seen that when load more data, the position of the scrollbar not changed. I am trying to implement the same thing but with React Hook using UseState as datasource .  When state changed the table totally be refreshed and scrollbar be reset to top. Could you explain a bit about the behavior the the table, how can I keep state of the table in this case?

Code Sandbox: https://codesandbox.io/s/testbasetableinfinitiveloading-3im20

Thanks,
TD

**Comment by mangkang** [comment]
Hi @dohoangtung ,

Did you figure out a solution for the re-render issue during scrolling? I notice similar issue with losing scrollbar positioning.

Thanks.

**Comment by nihgwu** [comment]
For @dohoangtung 's case, he made a mistake that `setState` of `useState` will replace the state instead of updating partially, here is a working version https://codesandbox.io/s/test-basetable-infinitiveloading-forked-3dn3j?file=/src/Table.js, change `setState(state)` to `setState(prevState => ({...prevState, ...state}))`

**Comment by mangkang** [comment]
Thanks for the quick reply. That helps!
