### ISSUE TITLE
How to implement show horizontal scrollbar when there has no data

### ISSUE THREAD

**Issue by dingchaoyan1983** [Autodesk/react-base-table#38]
I don't know whether this is a bug, when the total width of header is exceed the table width. if there is no data, the horizontal scrollbar will not be shown, only there are some data on table body, the horizontal scrollbar shown

**Comment by nihgwu** [comment]
That’s by design, as it’s supposed to show the EmptyState if there is no data, with frozen columns there are 3 internal table an there is no way to keep the EmptyState centered and keep still even when scroll horizontally
If you do need that, I guess you could provide some dummy data and make the rowHeight=0?

**Comment by dingchaoyan1983** [comment]
This is a good idea, thank you
