### ISSUE TITLE
能否支持多列排序 (Does it support sorting on multiple columns)

### ISSUE THREAD

**Issue by Nokecy** [Autodesk/react-base-table#7]

**Comment by nihgwu** [comment]
I'd say the BaseTable does not data sorting actually, it just uses `sortBy` to show the `SortIndicator`, by default it just show the `SortIndicator` in one column's header, but you could show more via changing the styles

Right now `sortBy` receives an object instead of an array, but you could save the `[sortBy]` state on your own, and apply className to the headers via `headerClassName`

**Comment by Nokecy** [comment]
I don't quite understand, can you give me a pseudo code?

**Comment by nihgwu** [comment]
I will add more demos later, including auto size you asked in another thread

**Comment by Nokecy** [comment]
Thank you!

**Comment by nihgwu** [comment]
https://autodesk.github.io/react-base-table/examples/multi-sort
seems I should add multi sort in the component instead of style hack

**Comment by Nokecy** [comment]
https://github.com/Autodesk/react-base-table/blob/5b8683810fefd7830f8677e81e887d1713742de1/src/BaseTable.js#L362

`const sorting = column.key === sortBy[key]; `

Changing the sortBy type is better like this:
`const sortBy= {
  'column-0': 'asc',
  'column-1': 'desc',
  'column-2': 'asc',
}
`

**Comment by nihgwu** [comment]
@Nokecy Yes, but that would be a breaking change, I will figure out a way later
